"""nono

Revision ID: 2197388476e8
Revises: 5f7481e52430
Create Date: 2024-06-28 18:36:26.090887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2197388476e8'
down_revision = '5f7481e52430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=False))
        batch_op.drop_column('auther')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auther', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
