"""book

Revision ID: 4e3ddd948163
Revises: 5dda82864a9e
Create Date: 2024-06-28 13:02:04.512706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3ddd948163'
down_revision = '5dda82864a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covers',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('MIME_type', sa.String(length=250), nullable=False),
    sa.Column('MD5_hash', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('publish', sa.Integer(), nullable=False),
    sa.Column('auther', sa.String(length=100), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('cover_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cover_id'], ['covers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('covers')
    # ### end Alembic commands ###
